### ISSUE TITLE
Suggestion: Sugar for call-attr and call-attr-kw

### ISSUE THREAD

**Issue by davidpham87** [cnuernber/libpython-clj#1]
Hello,

First of all, this is a great project and I wish we could see it being the standard way to interact with python and Clojure!

It is only a small detail with respect to the all difficulties you might have for creating a bridge between python and Clojure, but would it make sense to create some sort of sugar/interface/macro to call functions from modules with would look like either namespace calling, e.g `np/zeros` for modules or like `(.attr object & args)` or
`(.attr object & kwargs)` for modules and object.

**Comment by cnuernber** [comment]
Thank you, my hope is to allow clojure and python it deeply intermix give both python and clojure people incremental and efficient pathways to work together.
 
I completely agree about syntax.  I would personally vote for building out namespaces so for instance a numpy namespace.  Let's see if anyone else chimes in.

**Comment by cnuernber** [comment]
This issue is solved by Alan Marazzi's [panthera](https://github.com/alanmarazzi/panthera).

**Comment by davidpham87** [comment]
Just about syntax, we could inspire ourselves from Hy (lisp for python), for function call:

http://docs.hylang.org/en/stable/tutorial.html

They use a `#*` and `#**` for the python equivalent.

**Comment by cnuernber** [comment]
The general direction I like.  Some sugar around keyword arguments would be nice; I think it might take the form of a macro or something that analyzed the argument types and if there were an odd number of arguments after the first keyword argument would default to call-kw.

This:
```hy
(optional-arg #* args #** kwargs)
[1, 2, 4, 3]
```

Would expand directly to:
```clojure
(call-kw optional-arg args kwargs)
```

What we don't have is the python compiler deciding what goes in the arglist and the keyword argmap; I believe this would have to be done by a macro.

**Comment by cnuernber** [comment]
I should add that I know Alan has experimented with a couple different directions here and he is still working on it.  I think Panthera has a couple motivational examples.

**Comment by davidpham87** [comment]
I still believe that modules should have the namespace syntax, but I like how Alan solved the problem for numpy.
