### ISSUE TITLE
bridged def missing from README

### ISSUE THREAD

**Issue by sogaiu** [cnuernber/libpython-clj#11]
Commit https://github.com/cnuernber/libpython-clj/commit/edd221dc019e178a835fec12106574bb0f6af710 appears to have removed the `def` for `bridged`: 
```
(def bridged (->> *1
                        (map (fn [[k v]]
                               [k (as-jvm v)]))
                        (into {})))
```
That makes the current code in the README:

```
(instance? java.util.Map (:globals bridged))
```

not work.

**Comment by cnuernber** [comment]
Thanks for the heads up, documentation is updated!
