### ISSUE TITLE
Have generic wrappers derive from appropriate ABC objects

### ISSUE THREAD

**Issue by cnuernber** [cnuernber/libpython-clj#33]
This avoids issues like:
```console
lein test :only panthera.generics-test/head

ERROR in (head) (interpreter.clj:385)
expected: (= (u/->clj (g/head (g/data-frame (flatten (repeat 5 [{:a 1, :b 2} {:a 2, :
  actual: java.lang.Exception: Traceback (most recent call last):
  File "/mnt/DATA/miniconda3/envs/panthera/lib/python3.7/site-packages/pandas/core/fr
    elif isinstance(data, abc.Iterable) and not isinstance(data, (str, bytes)):
  File "/mnt/DATA/miniconda3/envs/panthera/lib/python3.7/abc.py", line 139, in __inst
    return _abc_instancecheck(cls, instance)
  File "/mnt/DATA/miniconda3/envs/panthera/lib/python3.7/abc.py", line 143, in __subc
    return _abc_subclasscheck(cls, subclass)
TypeError: issubclass() arg 1 must be a class
```

**Comment by jjtolton** [comment]
Can we rule out that this is unrelated?
https://bugs.python.org/issue34760

**Comment by cnuernber** [comment]
No, I think it is related.  The pandas code is calling isinstance and it appears like the abc code itself is just generically forwarding to issubclass and that is a bug.  
That being said, I bet of the iterator derives from ABC.Iterator that would make this issue go away.

* [pandas code](https://github.com/pandas-dev/pandas/blob/master/pandas/core/frame.py#L452)
* [abc code](https://github.com/python/cpython/blob/3.7/Lib/abc.py)

**Comment by jjtolton** [comment]
I think in this case it's fine to wrap iterators with `abc.Iterator`, but should be careful of:

1.  providing overly specific generic wrappers to Python and
2.  not try to fix Python (or Clojure's bugs) -- I think that could bite us when they fix them later

**Comment by cnuernber** [comment]
Agreed on both counts.

**Comment by cnuernber** [comment]
https://github.com/cnuernber/libpython-clj/releases/tag/1.28
