### ISSUE TITLE
Sequences

### ISSUE THREAD

**Issue by alanmarazzi** [cnuernber/libpython-clj#34]
Sequences (1.24+) are breaking how panthera works, basically this works:

```clojure
(pt/data-frame (vec (flatten (repeat 5 [{:a 1 :b 2} {:a 2 :b 3}]))))
```

But this doesn't:

```clojure
(pt/data-frame (flatten (repeat 5 [{:a 1 :b 2} {:a 2 :b 3}])))
```
```python
Execution error at libpython-clj.python.interpreter/check-error-throw (interpreter.clj:506).
Traceback (most recent call last):
  File "/mnt/DATA/miniconda3/envs/panthera/lib/python3.7/site-packages/pandas/core/frame.py", line 443, in __init__
    elif isinstance(data, abc.Iterable) and not isinstance(data, (str, bytes)):
  File "/mnt/DATA/miniconda3/envs/panthera/lib/python3.7/abc.py", line 139, in __instancecheck__
    return _abc_instancecheck(cls, instance)
  File "/mnt/DATA/miniconda3/envs/panthera/lib/python3.7/abc.py", line 143, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
TypeError: issubclass() arg 1 must be a class
```

Just as a reference, this breaks in the same way:

```clojure
(require-python '[pandas :as pd])
(pd/DataFrame (flatten (repeat 5 [{:a 1 :b 2} {:a 2 :b 3}])))
```

I'm already sanitizing user input a lot (https://github.com/alanmarazzi/panthera/blob/e16d254d7d8048af0381cbf2e3285a77db517fb2/src/panthera/pandas/utils.clj#L229) because pandas expects fully realized objects shaped in a certain way to actually work.

P.S.: refer to the dev branch since there's a lot of stuff that isn't in master yet

**Comment by jjtolton** [comment]
```quote
Sequences (1.24+) are breaking how panthera works, basically this works:

(pt/data-frame (vec (flatten (repeat 5 [{:a 1 :b 2} {:a 2 :b 3}]))))
But this doesn't:

(pt/data-frame (flatten (repeat 5 [{:a 1 :b 2} {:a 2 :b 3}])))
```
`flatten` is a LazySeq.  

The reason this is breaking since 1.24+ is that in 1.24+, @cnuernber changed it so that lazy seqs do not fully realize before they're passed in to Python.

**Comment by cnuernber** [comment]
Potentially fixed by:
https://github.com/cnuernber/libpython-clj/releases/tag/1.28

**Comment by jjtolton** [comment]
@alanmarazzi did it work??

**Comment by alanmarazzi** [comment]
Nope, I'm changing tests

**Comment by jjtolton** [comment]
Ah sorry to hear that.  I was hoping this would fix but looks like it might
be more complex than we thought.
