### ISSUE TITLE
require-python - (minor) - possibly inconsistent syntax

### ISSUE THREAD

**Issue by cnuernber** [cnuernber/libpython-clj#36]
```clojure
user> (require-python '(mxnet mxnet.module))
nil
user> (require-python '[mxnet mxnet.module])
Execution error (IllegalArgumentException) at libpython-clj.require/python-lib-configuration (require.clj:306).
Vector arg to map conj must be a pair
```

**Comment by jjtolton** [comment]
Yeah I was just thinking about that today.  I should probably `core.spec` that with some more helpful error messages. The spec should be `'namespace` or `(ns1 ns2)` or `(req1 [ns2 :as alias ~@etc] ~@reqs)`

**Comment by jjtolton** [comment]
Proposed enhancement:  add `core.spec` pre/post conditions

**Comment by cnuernber** [comment]
This seems fine to me and actually matches pretty closely what happens when I do a normal clojure require statement.
