### ISSUE TITLE
Bridge chars to string length 1

### ISSUE THREAD

**Issue by jjtolton** [cnuernber/libpython-clj#39]
expected: 
```clojure 
(python/str \a) ;;=> "a"
```
actual: :boom: 
```java 
Unable to convert objects of type: class java.lang.Character
```

**Comment by jjtolton** [comment]
This comes up frequently in iteration contexts and membership tests.

**Comment by cnuernber** [comment]
https://github.com/cnuernber/libpython-clj/commit/b1ea809db27782ede88174eb856b27a6dcdb95d7
