### ISSUE TITLE
Is type check possible for Python types?

### ISSUE THREAD

**Issue by dragoon000320** [cnuernber/libpython-clj#42]
Hi @cnuernber,
thank you for the great library. I just wonder whether is it possible to utilize type checking for Python types. Unfortunately, I haven't found any reference in a source code.
Thanks in advance

**Comment by cnuernber** [comment]
I am not certain what you mean.  Python is dynamically typed so you can't do a static typecheck.

We do expose the c library function [is-instance?](https://github.com/cnuernber/libpython-clj/blob/master/src/libpython_clj/python.clj#L57) and you can require-python builtins to get the python [isinstance](https://github.com/cnuernber/libpython-clj/blob/master/src/libpython_clj/metadata.clj#L31) call. 

Does this solve your issue?

**Comment by cnuernber** [comment]
Or do you mean [python static type checking](https://realpython.com/python-type-checking/)?  If you do mean this, then that is a python compiler pathway and and the support we have for that is `:reload` in require-python.

**Comment by dragoon000320** [comment]
"is-instance?" is exactly what I wanted, thanks for quick reply
