### ISSUE TITLE
difference in calling conventions leads to strange behavior in pandas

### ISSUE THREAD

**Issue by jjtolton** [cnuernber/libpython-clj#50]
Working hypothesis:  

There is a nuanced difference between the behavior of 
`(f *args **kwargs)` and `(py/call-kw f args kwargs)` in some rare edge cases that seem to come up frequently in Pandas.

It seems that all the breaking pathways lead to `(f *args **kwargs)` and all the working pathways converge on `(py/call-kw f args kwargs)`

### Working

Each of the following examples converge to `py/call-kw`.

```clojure 
(let [data (doto (pd/DataFrame {:index [1 2] :value [2 3] :variable [1 1]})
               (py. melt :id_vars "index"))]
    (py. px line :data_frame data :x "index" :y "value" :color "variable")) ;; works

(let [data (doto (pd/DataFrame {:index [1 2] :value [2 3] :variable [1 1]})
               (py. melt :id_vars "index"))]
    (py/call-attr-kw px "line" nil {:data_frame data :x "index" :y "value" :color "variable"})) ;; works

(let [data
        (doto
            (pd/DataFrame {:index [1 2] :value [2 3] :variable [1 1]})
          (py. melt :id_vars "index"))]
    (py/call-kw px/line nil {:data_frame data :x "index" :y "value" :color "variable"})) ;; works

(let [data
        (doto
            (pd/DataFrame {:index [1 2] :value [2 3] :variable [1 1]})
          (py. melt :id_vars "index"))]
    (py/call-kw (py.- px line ) nil {:data_frame data :x "index" :y "value" :color "variable"})) ;; works

(def px-line
    (let [{{:keys [line]} :globals}
          (py/run-simple-string
           "
import plotly.express as px

line = px.line
")] line))

(let [data
        (doto
            (pd/DataFrame {:index [1 2] :value [2 3] :variable [1 1]})
          (py. melt :id_vars "index"))]
    (py/call-kw px-line  nil {:data_frame data :x "index" :y "value" :color "variable"})) ;; works
```
### Breaking

Each of the following converge to `(f *args **kwargs)`

```clojure 
(let [data (doto (pd/DataFrame {:index [1 2] :value [2 3] :variable [1 1]})
               (py. melt :id_vars "index"))]
    ((py.- px line) :data_frame data :x "index" :y "value" :color "variable")) ;; breaks

(let [data (doto (pd/DataFrame {:index [1 2] :value [2 3] :variable [1 1]})
               (py. melt :id_vars "index"))]
    (px/line :data_frame data :x "index" :y "value" :color "variable")) ;; breaks

  (def px-line
    (let [{{:keys [line]} :globals}
          (py/run-simple-string
           "
import plotly.express as px

line = px.line
")] line))
  
  (let [data
        (doto
            (pd/DataFrame {:index [1 2] :value [2 3] :variable [1 1]})
          (py. melt :id_vars "index"))]
    (px-line :data_frame data :x "index" :y "value" :color "variable")) ;; breaks

```

**Comment by jjtolton** [comment]
@cnuernber one option -- not a holistic fix, but a fix that would handle most use cases: 

I can retool the functions/methods populated by `require-python` to use `(py/call-kw ...)`.  This would still lead to some inconsistencies if users access the lower level raw Python function, but I think it would handle the majority of use cases that users see.  The drawback would be a slight hit to performance (an additional nested function call) and the function employed would no longer be a true Python function but a Python function wrapped with a clojure function that calls `py/call-kw`.

**Comment by cnuernber** [comment]
I would like to take a careful look at this.  Everything filters through py/call-kw eventually.  The questions I have right now are twofold:
1.  Is this because of the marshalling layer on top of functions that attempts to ensure we don't deep-copy objects but we do shallow copy simple objects? 
2.  Is this because the system to detect kwargs via detecting keywords in the arguments? 

Basically, I want to know the exact mechanism of failure which could probably be found by printing out the arguments to PyObject_Call xxx.

**Comment by cnuernber** [comment]
Closing this, it works with the referenced changelist.

**Comment by cnuernber** [comment]
Screencase: https://drive.google.com/file/d/1PTXzWqNaRAiIDDZWqkeffIK2KESRWSRh/view?usp=sharing
