### ISSUE TITLE
Allow specification of Python executable

### ISSUE THREAD

**Issue by jjtolton** [cnuernber/libpython-clj#52]
Currently the Python3 executable path is [hardcoded](https://github.com/cnuernber/libpython-clj/blob/master/src/libpython_clj/python/interpreter.clj#L148) to `"python3"`.  I propose we allow the executable to be specified via `:python-executable` in `py/initialize!`.  On my system, Python3.6 always gets picked up first even though Python3.7 is available because Python3.6 is my current system alternative.  

This change should also allow use of Python virtual environments.

**Comment by gigasquid** [comment]
Whether libpython-clj works with a virtual environment has come up a lot in general questions/ interactions. I think this will be very beneficial. 🎉

**Comment by orolle** [comment]
I try to get libpython-clj work with anaconda on windows. The windows PATH environment variable for clojure.java.shell/sh is handled a little bit different compared to Linux & Mac. Thus the hardcoded "python3" makes it impossible to execute anything with clojure.java.shell/sh. Being able to parameterize the python-executable would work around windows specifics.
