### ISSUE TITLE
Symbols beginning or ending with '.' are reserved by Clojure

### ISSUE THREAD

**Issue by hiredman** [cnuernber/libpython-clj#68]
https://clojure.org/reference/reader#_symbols says:

> Symbols beginning or ending with '.' are reserved by Clojure

In particular clojure uses them as syntax sugar for `(new Whatever ...)`, this library defines several macros with names that end in '.' that for now happen to work as clojure itself doesn't enforce this reservation, but if it ever does it will break this library. And other tooling that respects this reservation breaks with this library

**Comment by jafingerhut** [comment]
Or at least maybe ping Alex Miller to see if he knows what possible limitations/issues/problems he sees with current Clojure code, if any.  It may scare you enough to want to change the names :-)

**Comment by cnuernber** [comment]
Good thoughts, will ask, thanks!

**Comment by cnuernber** [comment]
Every python user coming to Clojure will expect some level of '.' oriented interop.  In addition, anyone who knows the Clojure java interop will be familiar with the constructs that we have right now.  

If I was going to be scared by things that might happen there is no way I would have attempted to embed Python in Clojure using the raw C bindings.  I talked to Alex at length about this and at some point in the future they might change clojure such that this is an issue.

I am betting they won't.
