### ISSUE TITLE
Running on OSX

### ISSUE THREAD

**Issue by davidvoler** [cnuernber/libpython-clj#7]
I have tried running the example on osx. 
The way to do that was:
sudo find / -name libpython3.6m.dylib
And taking the first results:
(alter-var-root #'libpython-clj.jna.base/*python-library* (constantly "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/config-3.6m-darwin/libpython3.6m.dylib"))

I was wondering if there is an easy way to get the current python based on the context  (virtualenv, conda) and figure out the location of the libpython?

**Comment by cnuernber** [comment]
I would love to figure this out.  Environments are the hardest thing about something like this and automagically finding the python to use would be fantastic.  

I don't know the best way, however, to find the first libpython shared library on your path.    

The one way might be to somehow ask the linker what library would be loaded:
* [ubuntu linker docs](https://unix.stackexchange.com/questions/22926/where-do-executables-look-for-shared-objects-at-runtime).

I don't know an automated way to do this; I think most of those systems just reset $PATH.

**Comment by cnuernber** [comment]
Related to #2.

**Comment by cnuernber** [comment]
On ubuntu, `ldconfig -p`  prints out the shared libraries available:

```console
chrisn@chrisn-lt-2:~$ ldconfig -p | grep python
        libpython3.7m.so.1.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0
        libpython3.7m.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libpython3.7m.so
        libpython3.6m.so.1.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
        libpython3.6m.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libpython3.6m.so
        libpython2.7.so.1.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
        libpython2.7.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libpython2.7.so
        libpyglib-2.0-python2.7.so.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libpyglib-2.0-python2.7.so.0
        libboost_python3-py36.so.1.65.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_python3-py36.so.1.65.1
        libboost_python3-py36.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_python3-py36.so
        libboost_python-py27.so.1.65.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.65.1
        libboost_python-py27.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_python-py27.so
```

**Comment by cnuernber** [comment]
Closing for now as this issue has stalled.  The best solution we have for now is to use docker to control the host environment.
